# Generated by Django 4.0.1 on 2022-06-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_taller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_genero', models.CharField(max_length=50, verbose_name='Nombre genero')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('sku', models.AutoField(primary_key=True, serialize=False, verbose_name='Rut')),
                ('autor', models.CharField(max_length=100, null=True, verbose_name='Nombre autor')),
                ('libro', models.CharField(max_length=100, null=True, verbose_name='Nombre libro')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_taller.genero')),
            ],
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='Taller',
        ),
    ]
