# Generated by Django 4.0.1 on 2022-06-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_taller', '0003_rename_libro_libro_nombrelibro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='sku',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Sku'),
        ),
    ]
