# Generated by Django 4.0.4 on 2022-06-30 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_taller', '0004_alter_libro_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=50, verbose_name='Nombre genero'),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
