# Generated by Django 4.0.4 on 2022-07-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_taller', '0006_alter_libro_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='dias',
            field=models.IntegerField(default=5, verbose_name='Dias prestamo'),
            preserve_default=False,
        ),
    ]
