# Generated by Django 4.0.5 on 2022-06-29 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombre_genero', models.CharField(max_length=50, verbose_name='Nombre genero')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rutUser', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombreUser', models.CharField(max_length=100, null=True, verbose_name='Nombre autor')),
                ('correoUser', models.CharField(max_length=100, null=True, verbose_name='Nombre libro')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_app.genero')),
            ],
        ),
    ]
