# Generated by Django 4.0.5 on 2022-06-30 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth_app', '0002_remove_user_genero_delete_genero_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoUsu',
            fields=[
                ('idUsu', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('nomTipo', models.CharField(max_length=30, verbose_name='Tipo Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Correo')),
                ('password', models.CharField(max_length=60, verbose_name='Clave')),
                ('personaNom', models.CharField(max_length=120, verbose_name='Nombre Persona')),
                ('apellido', models.CharField(max_length=120, verbose_name='Apellido Completo')),
                ('numTelefono', models.IntegerField(verbose_name='Numero Telefono')),
                ('direccion', models.CharField(max_length=120, verbose_name='Direccion')),
                ('tipoUsu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth_app.tipousu', verbose_name='Tipo Usuario')),
            ],
        ),
    ]
