# Generated by Django 4.0.4 on 2022-06-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipo', '0003_alter_docente_apellidomat_alter_docente_apellidopat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipo/static/Docentes', verbose_name='Imagen'),
        ),
    ]
