# Generated by Django 4.0.4 on 2022-07-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prestamo', models.IntegerField(verbose_name='cod_Prestamo')),
                ('lista_libros', models.CharField(max_length=200, verbose_name='lista')),
                ('email', models.CharField(max_length=120, verbose_name='Correo')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
