# Generated by Django 4.0.4 on 2022-07-12 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_prestamo_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='status',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.IntegerField(default=0, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fechaDevolucion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha devolucion'),
            preserve_default=False,
        ),
    ]
