# Generated by Django 4.0.4 on 2022-05-10 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidoPat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apelido Paterno')),
                ('apellidoMat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apelido Materno')),
                ('password', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.tipousuario')),
            ],
        ),
    ]
