# Generated by Django 4.0.4 on 2022-05-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Correo'),
        ),
    ]
