# Generated by Django 4.0.4 on 2022-05-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_usuario_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Asignatura',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Asignatura'),
        ),
    ]
