# Generated by Django 4.0.4 on 2022-05-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_usuario_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Imagen'),
        ),
    ]
