# Generated by Django 4.0.4 on 2022-05-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='login/static/login/users', verbose_name='Imagen'),
        ),
    ]
